### ISSUE TITLE
Laravel 11 config:publish

### ISSUE THREAD

**Issue by nam-co** [TeriyakiBomb/nova-artisan#1]
Hi @TeriyakiBomb , thanks for the work on this extension, since V11 is around the corner it would be cool to have "config:publish" and maybe ask the file name or leave empty and publish all

```
nova.commands.register("laravel-artisan.configPublish", (options) => {
  runLaravelCommand({
    command: "config:publish",
    successMessage: "♻️ Config published",
  });
});
```

https://github.com/laravel/framework/pull/47309

**Comment by TeriyakiBomb** [comment]
Hey! If you take a look at the latest commit and let me know if that works? I've added two new commands, one for all configs and another for selecting a specific config from a list. I don't have a Laravel 11 project running at the moment, I can't test this right now, but let me know if this works and if you have any other suggestions

**Comment by nam-co** [comment]
Hi, thanks for the update, I deleted the v11 testing 😂 non of the 3rd party worked, but the official release is around the corner, I will try it once is released, don't know why packages wait, normally most of them work in new versions, but thanks @TeriyakiBomb I also saw your image package 👍👍

**Comment by TeriyakiBomb** [comment]
No probs, we can have a look once v11 is release proper, I've not submitted this to Panic yet anyway. I'll leave the issue open for now

The image placeholder thing? Yeah, not been very popular sadly :( You should try out my theme though! I'm pretty proud of it :) https://extensions.panic.com/extensions/teriyaki/teriyaki.Ashokai/
